import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BoardProvider } from "./context/BoardContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        suppressHydrationWarning // Remoiving the warning
        className={'antialiased min-h-screen text-slate-900 bg-gradient-to-tr from-[#81a3d5] via-[#6d95c3] to-[#c74f4f] bg-fixed'}
      >
        <BoardProvider>
          {children}
        </BoardProvider>
      </body>
    </html>
  );
}
